# -*- coding:utf-8 -*-
"""
@Author   : g1879
@Contact  : g1879@qq.com
@Copyright: (c) 2024 by g1879, Inc. All Rights Reserved.
@License  : BSD 3-Clause.
"""
from typing import Union, List, Optional, Iterable

from .._base.base import BaseParser
from .._elements.chromium_element import ChromiumElement


def get_eles(locators: Union[List[str], tuple],
             owner: BaseParser,
             any_one: bool = False,
             first_ele: bool = True,
             timeout: float = 10) -> dict: ...


class ElementsList(list):
    _page = ...
    _filter: Optional[Filter] = ...
    _filter_one: Optional[FilterOne] = ...
    _getter: Optional[Getter] = ...

    @property
    def filter(self) -> Filter: ...

    @property
    def filter_one(self) -> FilterOne: ...

    @property
    def get(self) -> Getter: ...

    def search(self,
               displayed: Optional[bool] = None,
               checked: Optional[bool] = None,
               selected: Optional[bool] = None,
               enabled: Optional[bool] = None,
               clickable: Optional[bool] = None,
               have_rect: Optional[bool] = None,
               have_text: Optional[bool] = None) -> Filter: ...

    def search_one(self,
                   displayed: Optional[bool] = None,
                   checked: Optional[bool] = None,
                   selected: Optional[bool] = None,
                   enabled: Optional[bool] = None,
                   clickable: Optional[bool] = None,
                   have_rect: Optional[bool] = None,
                   have_text: Optional[bool] = None) -> ChromiumElement: ...

    def __next__(self) -> ChromiumElement: ...


class BaseFilter(object):
    _list: ElementsList = ...

    def __init__(self, _list: ElementsList): ...

    def displayed(self, equal: bool = True): ...

    def checked(self, equal: bool = True): ...

    def selected(self, equal: bool = True): ...

    def enabled(self, equal: bool = True): ...

    def clickable(self, equal: bool = True): ...

    def have_rect(self, equal: bool = True): ...

    def style(self, name: str, value: str, equal: bool = True): ...

    def property(self,
                 name: str,
                 value: str,
                 equal: bool = True): ...

    def attr(self, name: str, value: str, equal: bool = True): ...

    def _get_attr(self,
                  name: str,
                  value: str,
                  method: str,
                  equal: bool = True): ...

    def _any_state(self, name: str, equal: bool = True): ...


class Filter:
    _list: ElementsList = ...

    def __init__(self, _list: ElementsList): ...

    def __iter__(self) -> Iterable[ChromiumElement]: ...

    def __next__(self) -> ChromiumElement: ...

    @property
    def get(self) -> Getter: ...

    def displayed(self, equal: bool = True) -> Filter: ...

    def checked(self, equal: bool = True) -> Filter: ...

    def selected(self, equal: bool = True) -> Filter: ...

    def enabled(self, equal: bool = True) -> Filter: ...

    def clickable(self, equal: bool = True) -> Filter: ...

    def have_rect(self, equal: bool = True) -> Filter: ...

    def style(self, name: str, value: str, equal: bool = True) -> Filter: ...

    def property(self,
                 name: str,
                 value: str, equal: bool = True) -> Filter: ...

    def attr(self, name: str, value: str, equal: bool = True) -> Filter: ...

    def text(self, text: str, fuzzy: bool = True, contain: bool = True) -> Filter: ...

    def search(self,
               displayed: Optional[bool] = None,
               checked: Optional[bool] = None,
               selected: Optional[bool] = None,
               enabled: Optional[bool] = None,
               clickable: Optional[bool] = None,
               have_rect: Optional[bool] = None,
               have_text: Optional[bool] = None) -> Filter: ...

    def search_one(self,
                   displayed: Optional[bool] = None,
                   checked: Optional[bool] = None,
                   selected: Optional[bool] = None,
                   enabled: Optional[bool] = None,
                   clickable: Optional[bool] = None,
                   have_rect: Optional[bool] = None,
                   have_text: Optional[bool] = None) -> ChromiumElement: ...

    def _get_attr(self,
                  name: str,
                  value: str,
                  method: str, equal: bool = True) -> Filter: ...

    def _any_state(self, name: str, equal: bool = True) -> Filter: ...


class FilterOne(BaseFilter):
    _list: ElementsList = ...

    def __init__(self, _list: ElementsList): ...

    def displayed(self, equal: bool = True) -> ChromiumElement: ...

    def checked(self, equal: bool = True) -> ChromiumElement: ...

    def selected(self, equal: bool = True) -> ChromiumElement: ...

    def enabled(self, equal: bool = True) -> ChromiumElement: ...

    def clickable(self, equal: bool = True) -> ChromiumElement: ...

    def have_rect(self, equal: bool = True) -> ChromiumElement: ...

    def style(self, name: str, value: str, equal: bool = True) -> ChromiumElement: ...

    def property(self,
                 name: str,
                 value: str, equal: bool = True) -> ChromiumElement: ...

    def attr(self, name: str, value: str, equal: bool = True) -> ChromiumElement: ...

    def text(self, text: str, fuzzy: bool = True, contain: bool = True) -> ChromiumElement: ...

    def _get_attr(self,
                  name: str,
                  value: str,
                  method: str, equal: bool = True) -> ChromiumElement: ...

    def _any_state(self, name: str, equal: bool = True) -> ChromiumElement: ...


class Getter(object):
    _list: ElementsList = ...

    def __init__(self, _list: ElementsList): ...

    def links(self) -> List[str]: ...

    def texts(self) -> List[str]: ...

    def attrs(self, name: str) -> List[str]: ...
